[package]
name = "trimsec"
description = "Strategic (& fast) content consumption planner."
authors = ["HitBlast <hitblastlive@gmail.com>"]
version = "0.1.9"
edition = "2021"
repository = "https://github.com/hitblast/trimsec"
homepage = "https://github.com/hitblast/trimsec"
license = "MIT"
readme = "README.md"
exclude = ["assets/*"]

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
colored = "2.2.0"
