[package]
name = "trimsec"
description = "Calculate time saved on using speed multipliers."
authors = ["HitBlast <hitblastlive@gmail.com>"]
version = "1.0.1"
edition = "2024"
repository = "https://github.com/hitblast/trimsec"
homepage = "https://github.com/hitblast/trimsec"
license = "MIT"
readme = "README.md"
exclude = ["assets/*"]

[[bin]]
name = "ts"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
