[package]
name = "trimsec"
description = "Calculate time saved on using speed multipliers."
authors = ["HitBlast <hitblastlive@gmail.com>"]
version = "1.0.0"
edition = "2024"
repository = "https://github.com/hitblast/trimsec"
homepage = "https://github.com/hitblast/trimsec"
license = "MIT"
readme = "README.md"
exclude = ["assets/*"]

[dependencies]
clap = { version = "4", features = ["derive"] }
colored = "3"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
