[package]
name = "trimsec"
description = "Calculate saved time on using media speed multipliers, with speed."
authors = ["HitBlast <hitblastlive@gmail.com>"]
version = "0.1.4"
edition = "2021"
repository = "https://github.com/hitblast/trimsec"
homepage = "https://github.com/hitblast/trimsec"
license = "MIT"
readme = "README.md"
exclude = ["assets/*"]

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
colored = "2.2.0"
