[package]
name = "timetrim"
description = "Calculate saved time on speed multipliers, with speed."
authors = ["HitBlast <hitblastlive@gmail.com>"]
version = "0.1.0"
edition = "2021"
repository = "https://github.com/hitblast/timetrim"
license = "MIT"
readme = "README.md"

[dependencies]
