.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH trimsec 1  "trimsec 2.2.1" 
.SH NAME
trimsec \- Calculate time saved on using speed multipliers.
.SH SYNOPSIS
\fBtrimsec\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Calculate time saved on using speed multipliers.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
trimsec\-trim(1)
Calculate basic duration with multipliers
.TP
trimsec\-yt(1)
Calculate for YouTube videos
.TP
trimsec\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v2.2.1
