name: Release Builds

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --release --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: trimsec-win-latest
          path: target/release/deps/trimsec.exe
          retention-days: 90

  build-unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --release --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: trimsec-${{ matrix.os }}
          path: target/release/trimsec
          retention-days: 90

  publish:
    needs: [build-win]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish using cargo
        run: cargo publish --token ${{ secrets.CRATES_TOKEN }}
