name: Unit Tests

on:
  push:
    paths:
      - "**.rs"
  pull_request:
    paths:
      - "**.rs"
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run tests
        run: cargo test
